//go:build !ignore_autogenerated

/*
Copyright 2026 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	kaiv1 "github.com/kai-scheduler/KAI-scheduler/pkg/apis/kai/v1"
	"github.com/kai-scheduler/KAI-scheduler/pkg/apis/kai/v1/common"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteBlocker) DeepCopyInto(out *DeleteBlocker) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteBlocker.
func (in *DeleteBlocker) DeepCopy() *DeleteBlocker {
	if in == nil {
		return nil
	}
	out := new(DeleteBlocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Department) DeepCopyInto(out *Department) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Department.
func (in *Department) DeepCopy() *Department {
	if in == nil {
		return nil
	}
	out := new(Department)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Department) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepartmentCondition) DeepCopyInto(out *DepartmentCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepartmentCondition.
func (in *DepartmentCondition) DeepCopy() *DepartmentCondition {
	if in == nil {
		return nil
	}
	out := new(DepartmentCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepartmentList) DeepCopyInto(out *DepartmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Department, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepartmentList.
func (in *DepartmentList) DeepCopy() *DepartmentList {
	if in == nil {
		return nil
	}
	out := new(DepartmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DepartmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepartmentSpec) DeepCopyInto(out *DepartmentSpec) {
	*out = *in
	if in.Queues != nil {
		in, out := &in.Queues, &out.Queues
		*out = make([]QueueConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepartmentSpec.
func (in *DepartmentSpec) DeepCopy() *DepartmentSpec {
	if in == nil {
		return nil
	}
	out := new(DepartmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepartmentStatus) DeepCopyInto(out *DepartmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DepartmentCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepartmentStatus.
func (in *DepartmentStatus) DeepCopy() *DepartmentStatus {
	if in == nil {
		return nil
	}
	out := new(DepartmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FairShareSampling) DeepCopyInto(out *FairShareSampling) {
	*out = *in
	if in.FetchInterval != nil {
		in, out := &in.FetchInterval, &out.FetchInterval
		*out = new(string)
		**out = **in
	}
	if in.StalenessPeriod != nil {
		in, out := &in.StalenessPeriod, &out.StalenessPeriod
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FairShareSampling.
func (in *FairShareSampling) DeepCopy() *FairShareSampling {
	if in == nil {
		return nil
	}
	out := new(FairShareSampling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FairShareWindow) DeepCopyInto(out *FairShareWindow) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.TumblingStartTime != nil {
		in, out := &in.TumblingStartTime, &out.TumblingStartTime
		*out = (*in).DeepCopy()
	}
	if in.CronString != nil {
		in, out := &in.CronString, &out.CronString
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FairShareWindow.
func (in *FairShareWindow) DeepCopy() *FairShareWindow {
	if in == nil {
		return nil
	}
	out := new(FairShareWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfig) DeepCopyInto(out *GlobalConfig) {
	*out = *in
	if in.SchedulerName != nil {
		in, out := &in.SchedulerName, &out.SchedulerName
		*out = new(string)
		**out = **in
	}
	if in.QueueLabelKey != nil {
		in, out := &in.QueueLabelKey, &out.QueueLabelKey
		*out = new(string)
		**out = **in
	}
	if in.NodePoolLabelKey != nil {
		in, out := &in.NodePoolLabelKey, &out.NodePoolLabelKey
		*out = new(string)
		**out = **in
	}
	if in.DefaultNodePoolName != nil {
		in, out := &in.DefaultNodePoolName, &out.DefaultNodePoolName
		*out = new(string)
		**out = **in
	}
	if in.FinalizerDomain != nil {
		in, out := &in.FinalizerDomain, &out.FinalizerDomain
		*out = new(string)
		**out = **in
	}
	if in.NamespaceProjectLabelKey != nil {
		in, out := &in.NamespaceProjectLabelKey, &out.NamespaceProjectLabelKey
		*out = new(string)
		**out = **in
	}
	if in.ProjectLabelKey != nil {
		in, out := &in.ProjectLabelKey, &out.ProjectLabelKey
		*out = new(string)
		**out = **in
	}
	if in.EnforceSchedulerAnnotationKey != nil {
		in, out := &in.EnforceSchedulerAnnotationKey, &out.EnforceSchedulerAnnotationKey
		*out = new(string)
		**out = **in
	}
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.LeaderElection != nil {
		in, out := &in.LeaderElection, &out.LeaderElection
		*out = new(bool)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.RequireDefaultPodAntiAffinityTerm != nil {
		in, out := &in.RequireDefaultPodAntiAffinityTerm, &out.RequireDefaultPodAntiAffinityTerm
		*out = new(bool)
		**out = **in
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(string)
		**out = **in
	}
	if in.Openshift != nil {
		in, out := &in.Openshift, &out.Openshift
		*out = new(bool)
		**out = **in
	}
	if in.FipsMode != nil {
		in, out := &in.FipsMode, &out.FipsMode
		*out = new(FipsMode)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(ServiceMonitorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfig.
func (in *GlobalConfig) DeepCopy() *GlobalConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfig) DeepCopyInto(out *KRMConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfig.
func (in *KRMConfig) DeepCopy() *KRMConfig {
	if in == nil {
		return nil
	}
	out := new(KRMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KRMConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfigList) DeepCopyInto(out *KRMConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KRMConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfigList.
func (in *KRMConfigList) DeepCopy() *KRMConfigList {
	if in == nil {
		return nil
	}
	out := new(KRMConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KRMConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfigSpec) DeepCopyInto(out *KRMConfigSpec) {
	*out = *in
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = new(GlobalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodePoolController != nil {
		in, out := &in.NodePoolController, &out.NodePoolController
		*out = new(NodePoolController)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectController != nil {
		in, out := &in.ProjectController, &out.ProjectController
		*out = new(ProjectController)
		(*in).DeepCopyInto(*out)
	}
	if in.PodGroupAssigner != nil {
		in, out := &in.PodGroupAssigner, &out.PodGroupAssigner
		*out = new(PodGroupAssigner)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfigSpec.
func (in *KRMConfigSpec) DeepCopy() *KRMConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KRMConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfigStatus) DeepCopyInto(out *KRMConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfigStatus.
func (in *KRMConfigStatus) DeepCopy() *KRMConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KRMConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNodesConfig) DeepCopyInto(out *ManagedNodesConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNodesConfig.
func (in *ManagedNodesConfig) DeepCopy() *ManagedNodesConfig {
	if in == nil {
		return nil
	}
	out := new(ManagedNodesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedNodesConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNodesConfigList) DeepCopyInto(out *ManagedNodesConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedNodesConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNodesConfigList.
func (in *ManagedNodesConfigList) DeepCopy() *ManagedNodesConfigList {
	if in == nil {
		return nil
	}
	out := new(ManagedNodesConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedNodesConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNodesConfigSpec) DeepCopyInto(out *ManagedNodesConfigSpec) {
	*out = *in
	in.InclusionCriteria.DeepCopyInto(&out.InclusionCriteria)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNodesConfigSpec.
func (in *ManagedNodesConfigSpec) DeepCopy() *ManagedNodesConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedNodesConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNodesConfigStatus) DeepCopyInto(out *ManagedNodesConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNodesConfigStatus.
func (in *ManagedNodesConfigStatus) DeepCopy() *ManagedNodesConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedNodesConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInNodePool) DeepCopyInto(out *NodeInNodePool) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInNodePool.
func (in *NodeInNodePool) DeepCopy() *NodeInNodePool {
	if in == nil {
		return nil
	}
	out := new(NodeInNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool) DeepCopyInto(out *NodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool.
func (in *NodePool) DeepCopy() *NodePool {
	if in == nil {
		return nil
	}
	out := new(NodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolCondition) DeepCopyInto(out *NodePoolCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolCondition.
func (in *NodePoolCondition) DeepCopy() *NodePoolCondition {
	if in == nil {
		return nil
	}
	out := new(NodePoolCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolController) DeepCopyInto(out *NodePoolController) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(common.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.ControllerService != nil {
		in, out := &in.ControllerService, &out.ControllerService
		*out = new(NodePoolControllerService)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhooks != nil {
		in, out := &in.Webhooks, &out.Webhooks
		*out = new(NodePoolControllerWebhooks)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = new(NodePoolControllerArgs)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolController.
func (in *NodePoolController) DeepCopy() *NodePoolController {
	if in == nil {
		return nil
	}
	out := new(NodePoolController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolControllerArgs) DeepCopyInto(out *NodePoolControllerArgs) {
	*out = *in
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(bool)
		**out = **in
	}
	if in.LeaderElect != nil {
		in, out := &in.LeaderElect, &out.LeaderElect
		*out = new(bool)
		**out = **in
	}
	if in.MetricsNamespace != nil {
		in, out := &in.MetricsNamespace, &out.MetricsNamespace
		*out = new(string)
		**out = **in
	}
	if in.DcgmExporterNamespace != nil {
		in, out := &in.DcgmExporterNamespace, &out.DcgmExporterNamespace
		*out = new(string)
		**out = **in
	}
	if in.SchedulingShardArgs != nil {
		in, out := &in.SchedulingShardArgs, &out.SchedulingShardArgs
		*out = new(string)
		**out = **in
	}
	if in.ExcludedNodepoolName != nil {
		in, out := &in.ExcludedNodepoolName, &out.ExcludedNodepoolName
		*out = new(string)
		**out = **in
	}
	if in.ManagedNodesConfigName != nil {
		in, out := &in.ManagedNodesConfigName, &out.ManagedNodesConfigName
		*out = new(string)
		**out = **in
	}
	if in.ToExcludeLabel != nil {
		in, out := &in.ToExcludeLabel, &out.ToExcludeLabel
		*out = new(string)
		**out = **in
	}
	if in.UnschedulableLabel != nil {
		in, out := &in.UnschedulableLabel, &out.UnschedulableLabel
		*out = new(string)
		**out = **in
	}
	if in.GroveTopologyAnnotation != nil {
		in, out := &in.GroveTopologyAnnotation, &out.GroveTopologyAnnotation
		*out = new(string)
		**out = **in
	}
	if in.GroveTopologyResourceVersionAnnotation != nil {
		in, out := &in.GroveTopologyResourceVersionAnnotation, &out.GroveTopologyResourceVersionAnnotation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolControllerArgs.
func (in *NodePoolControllerArgs) DeepCopy() *NodePoolControllerArgs {
	if in == nil {
		return nil
	}
	out := new(NodePoolControllerArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolControllerService) DeepCopyInto(out *NodePoolControllerService) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(PortMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.NodePoolMetrics != nil {
		in, out := &in.NodePoolMetrics, &out.NodePoolMetrics
		*out = new(PortMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(PortMapping)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolControllerService.
func (in *NodePoolControllerService) DeepCopy() *NodePoolControllerService {
	if in == nil {
		return nil
	}
	out := new(NodePoolControllerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolControllerWebhooks) DeepCopyInto(out *NodePoolControllerWebhooks) {
	*out = *in
	if in.EnableNodePoolValidation != nil {
		in, out := &in.EnableNodePoolValidation, &out.EnableNodePoolValidation
		*out = new(bool)
		**out = **in
	}
	if in.CertSecretName != nil {
		in, out := &in.CertSecretName, &out.CertSecretName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolControllerWebhooks.
func (in *NodePoolControllerWebhooks) DeepCopy() *NodePoolControllerWebhooks {
	if in == nil {
		return nil
	}
	out := new(NodePoolControllerWebhooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolList) DeepCopyInto(out *NodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolList.
func (in *NodePoolList) DeepCopy() *NodePoolList {
	if in == nil {
		return nil
	}
	out := new(NodePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolSpec) DeepCopyInto(out *NodePoolSpec) {
	*out = *in
	if in.SchedulingShardConfig != nil {
		in, out := &in.SchedulingShardConfig, &out.SchedulingShardConfig
		*out = new(SchedulingShardConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolSpec.
func (in *NodePoolSpec) DeepCopy() *NodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(NodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolStatus) DeepCopyInto(out *NodePoolStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeInNodePool, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NodePoolCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolStatus.
func (in *NodePoolStatus) DeepCopy() *NodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(NodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupAssigner) DeepCopyInto(out *PodGroupAssigner) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(common.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.ControllerService != nil {
		in, out := &in.ControllerService, &out.ControllerService
		*out = new(PodGroupAssignerService)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhooks != nil {
		in, out := &in.Webhooks, &out.Webhooks
		*out = new(PodGroupAssignerWebhooks)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = new(PodGroupAssignerArgs)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupAssigner.
func (in *PodGroupAssigner) DeepCopy() *PodGroupAssigner {
	if in == nil {
		return nil
	}
	out := new(PodGroupAssigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupAssignerArgs) DeepCopyInto(out *PodGroupAssignerArgs) {
	*out = *in
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(bool)
		**out = **in
	}
	if in.LeaderElect != nil {
		in, out := &in.LeaderElect, &out.LeaderElect
		*out = new(bool)
		**out = **in
	}
	if in.UnexistingNodepoolSentinel != nil {
		in, out := &in.UnexistingNodepoolSentinel, &out.UnexistingNodepoolSentinel
		*out = new(string)
		**out = **in
	}
	if in.AnnotationNodepoolsKey != nil {
		in, out := &in.AnnotationNodepoolsKey, &out.AnnotationNodepoolsKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupAssignerArgs.
func (in *PodGroupAssignerArgs) DeepCopy() *PodGroupAssignerArgs {
	if in == nil {
		return nil
	}
	out := new(PodGroupAssignerArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupAssignerService) DeepCopyInto(out *PodGroupAssignerService) {
	*out = *in
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(PortMapping)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupAssignerService.
func (in *PodGroupAssignerService) DeepCopy() *PodGroupAssignerService {
	if in == nil {
		return nil
	}
	out := new(PodGroupAssignerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupAssignerWebhooks) DeepCopyInto(out *PodGroupAssignerWebhooks) {
	*out = *in
	if in.EnablePodWebhook != nil {
		in, out := &in.EnablePodWebhook, &out.EnablePodWebhook
		*out = new(bool)
		**out = **in
	}
	if in.CertSecretName != nil {
		in, out := &in.CertSecretName, &out.CertSecretName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupAssignerWebhooks.
func (in *PodGroupAssignerWebhooks) DeepCopy() *PodGroupAssignerWebhooks {
	if in == nil {
		return nil
	}
	out := new(PodGroupAssignerWebhooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortMapping) DeepCopyInto(out *PortMapping) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.TargetPort != nil {
		in, out := &in.TargetPort, &out.TargetPort
		*out = new(int32)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortMapping.
func (in *PortMapping) DeepCopy() *PortMapping {
	if in == nil {
		return nil
	}
	out := new(PortMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Profiling) DeepCopyInto(out *Profiling) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.APIPort != nil {
		in, out := &in.APIPort, &out.APIPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Profiling.
func (in *Profiling) DeepCopy() *Profiling {
	if in == nil {
		return nil
	}
	out := new(Profiling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectCondition) DeepCopyInto(out *ProjectCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectCondition.
func (in *ProjectCondition) DeepCopy() *ProjectCondition {
	if in == nil {
		return nil
	}
	out := new(ProjectCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectController) DeepCopyInto(out *ProjectController) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(common.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.ControllerService != nil {
		in, out := &in.ControllerService, &out.ControllerService
		*out = new(ProjectControllerService)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhooks != nil {
		in, out := &in.Webhooks, &out.Webhooks
		*out = new(ProjectControllerWebhooks)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(ProjectControllerFeatures)
		(*in).DeepCopyInto(*out)
	}
	if in.Profiling != nil {
		in, out := &in.Profiling, &out.Profiling
		*out = new(Profiling)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = new(ProjectControllerArgs)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraProjectRoleBindings != nil {
		in, out := &in.ExtraProjectRoleBindings, &out.ExtraProjectRoleBindings
		*out = make([]ProjectRoleBinding, len(*in))
		copy(*out, *in)
	}
	if in.RoleBindingsConfigMapName != nil {
		in, out := &in.RoleBindingsConfigMapName, &out.RoleBindingsConfigMapName
		*out = new(string)
		**out = **in
	}
	if in.DeleteBlockers != nil {
		in, out := &in.DeleteBlockers, &out.DeleteBlockers
		*out = make([]DeleteBlocker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectController.
func (in *ProjectController) DeepCopy() *ProjectController {
	if in == nil {
		return nil
	}
	out := new(ProjectController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectControllerArgs) DeepCopyInto(out *ProjectControllerArgs) {
	*out = *in
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(bool)
		**out = **in
	}
	if in.LeaderElect != nil {
		in, out := &in.LeaderElect, &out.LeaderElect
		*out = new(bool)
		**out = **in
	}
	if in.ProjectNamePrefix != nil {
		in, out := &in.ProjectNamePrefix, &out.ProjectNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDLabelKey != nil {
		in, out := &in.ProjectIDLabelKey, &out.ProjectIDLabelKey
		*out = new(string)
		**out = **in
	}
	if in.QueueDepartmentNameLabelKey != nil {
		in, out := &in.QueueDepartmentNameLabelKey, &out.QueueDepartmentNameLabelKey
		*out = new(string)
		**out = **in
	}
	if in.NamespaceVersionLabelKey != nil {
		in, out := &in.NamespaceVersionLabelKey, &out.NamespaceVersionLabelKey
		*out = new(string)
		**out = **in
	}
	if in.ResourceManualOverrideLabelKey != nil {
		in, out := &in.ResourceManualOverrideLabelKey, &out.ResourceManualOverrideLabelKey
		*out = new(string)
		**out = **in
	}
	if in.LimitRangeName != nil {
		in, out := &in.LimitRangeName, &out.LimitRangeName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectControllerArgs.
func (in *ProjectControllerArgs) DeepCopy() *ProjectControllerArgs {
	if in == nil {
		return nil
	}
	out := new(ProjectControllerArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectControllerFeatures) DeepCopyInto(out *ProjectControllerFeatures) {
	*out = *in
	if in.CreateNamespaces != nil {
		in, out := &in.CreateNamespaces, &out.CreateNamespaces
		*out = new(bool)
		**out = **in
	}
	if in.CreateRoleBindings != nil {
		in, out := &in.CreateRoleBindings, &out.CreateRoleBindings
		*out = new(bool)
		**out = **in
	}
	if in.ClusterWideSecret != nil {
		in, out := &in.ClusterWideSecret, &out.ClusterWideSecret
		*out = new(bool)
		**out = **in
	}
	if in.ClusterWideConfigMap != nil {
		in, out := &in.ClusterWideConfigMap, &out.ClusterWideConfigMap
		*out = new(bool)
		**out = **in
	}
	if in.ClusterWidePvc != nil {
		in, out := &in.ClusterWidePvc, &out.ClusterWidePvc
		*out = new(bool)
		**out = **in
	}
	if in.LimitRange != nil {
		in, out := &in.LimitRange, &out.LimitRange
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectControllerFeatures.
func (in *ProjectControllerFeatures) DeepCopy() *ProjectControllerFeatures {
	if in == nil {
		return nil
	}
	out := new(ProjectControllerFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectControllerService) DeepCopyInto(out *ProjectControllerService) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(PortMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(PortMapping)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectControllerService.
func (in *ProjectControllerService) DeepCopy() *ProjectControllerService {
	if in == nil {
		return nil
	}
	out := new(ProjectControllerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectControllerWebhooks) DeepCopyInto(out *ProjectControllerWebhooks) {
	*out = *in
	if in.EnableProjectValidation != nil {
		in, out := &in.EnableProjectValidation, &out.EnableProjectValidation
		*out = new(bool)
		**out = **in
	}
	if in.EnableDepartmentValidation != nil {
		in, out := &in.EnableDepartmentValidation, &out.EnableDepartmentValidation
		*out = new(bool)
		**out = **in
	}
	if in.CertSecretName != nil {
		in, out := &in.CertSecretName, &out.CertSecretName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectControllerWebhooks.
func (in *ProjectControllerWebhooks) DeepCopy() *ProjectControllerWebhooks {
	if in == nil {
		return nil
	}
	out := new(ProjectControllerWebhooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectQuotaStatus) DeepCopyInto(out *ProjectQuotaStatus) {
	*out = *in
	if in.Allocated != nil {
		in, out := &in.Allocated, &out.Allocated
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.AllocatedNonPreemptible != nil {
		in, out := &in.AllocatedNonPreemptible, &out.AllocatedNonPreemptible
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requested != nil {
		in, out := &in.Requested, &out.Requested
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectQuotaStatus.
func (in *ProjectQuotaStatus) DeepCopy() *ProjectQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectRoleBinding) DeepCopyInto(out *ProjectRoleBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectRoleBinding.
func (in *ProjectRoleBinding) DeepCopy() *ProjectRoleBinding {
	if in == nil {
		return nil
	}
	out := new(ProjectRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	if in.Queues != nil {
		in, out := &in.Queues, &out.Queues
		*out = make([]QueueConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultNodePools != nil {
		in, out := &in.DefaultNodePools, &out.DefaultNodePools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeletionType != nil {
		in, out := &in.DeletionType, &out.DeletionType
		*out = new(DeletionType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ProjectCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodePoolsQuotaStatuses != nil {
		in, out := &in.NodePoolsQuotaStatuses, &out.NodePoolsQuotaStatuses
		*out = make([]QuotaStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.QuotaStatus.DeepCopyInto(&out.QuotaStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueConfig) DeepCopyInto(out *QueueConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(QueueResourcesConfig)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueConfig.
func (in *QueueConfig) DeepCopy() *QueueConfig {
	if in == nil {
		return nil
	}
	out := new(QueueConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueResourcesConfig) DeepCopyInto(out *QueueResourcesConfig) {
	*out = *in
	out.GPU = in.GPU
	out.CPU = in.CPU
	out.Memory = in.Memory
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueResourcesConfig.
func (in *QueueResourcesConfig) DeepCopy() *QueueResourcesConfig {
	if in == nil {
		return nil
	}
	out := new(QueueResourcesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaStatus) DeepCopyInto(out *QuotaStatus) {
	*out = *in
	in.QueueStatus.DeepCopyInto(&out.QueueStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaStatus.
func (in *QuotaStatus) DeepCopy() *QuotaStatus {
	if in == nil {
		return nil
	}
	out := new(QuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingShardConfig) DeepCopyInto(out *SchedulingShardConfig) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PlacementStrategy != nil {
		in, out := &in.PlacementStrategy, &out.PlacementStrategy
		*out = new(kaiv1.PlacementStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.QueueDepthPerAction != nil {
		in, out := &in.QueueDepthPerAction, &out.QueueDepthPerAction
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MinRuntime != nil {
		in, out := &in.MinRuntime, &out.MinRuntime
		*out = new(kaiv1.MinRuntime)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make(map[string]kaiv1.PluginConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make(map[string]kaiv1.ActionConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.TimeBasedFairShare != nil {
		in, out := &in.TimeBasedFairShare, &out.TimeBasedFairShare
		*out = new(TimeBasedFairShare)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingShardConfig.
func (in *SchedulingShardConfig) DeepCopy() *SchedulingShardConfig {
	if in == nil {
		return nil
	}
	out := new(SchedulingShardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorSpec) DeepCopyInto(out *ServiceMonitorSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Accounting != nil {
		in, out := &in.Accounting, &out.Accounting
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorSpec.
func (in *ServiceMonitorSpec) DeepCopy() *ServiceMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemResource) DeepCopyInto(out *SystemResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemResource.
func (in *SystemResource) DeepCopy() *SystemResource {
	if in == nil {
		return nil
	}
	out := new(SystemResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeBasedFairShare) DeepCopyInto(out *TimeBasedFairShare) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.HistoricalUsageWeight != nil {
		in, out := &in.HistoricalUsageWeight, &out.HistoricalUsageWeight
		*out = new(float32)
		**out = **in
	}
	if in.HalfLifePeriod != nil {
		in, out := &in.HalfLifePeriod, &out.HalfLifePeriod
		*out = new(string)
		**out = **in
	}
	if in.Window != nil {
		in, out := &in.Window, &out.Window
		*out = new(FairShareWindow)
		(*in).DeepCopyInto(*out)
	}
	if in.Sampling != nil {
		in, out := &in.Sampling, &out.Sampling
		*out = new(FairShareSampling)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeBasedFairShare.
func (in *TimeBasedFairShare) DeepCopy() *TimeBasedFairShare {
	if in == nil {
		return nil
	}
	out := new(TimeBasedFairShare)
	in.DeepCopyInto(out)
	return out
}
